# Generated by Django 5.0.4 on 2024-08-26 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_botusers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid phone number')]),
        ),
    ]
